/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardWorkspacesIndexRouteImport } from './routes/dashboard/workspaces/index'
import { Route as DashboardWorkspacesWorkspaceSlugRouteImport } from './routes/dashboard/workspaces/$workspaceSlug'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/dashboard/tasks',
  path: '/dashboard/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/dashboard/account',
  path: '/dashboard/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesIndexRoute =
  DashboardWorkspacesIndexRouteImport.update({
    id: '/dashboard/workspaces/',
    path: '/dashboard/workspaces/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardWorkspacesWorkspaceSlugRoute =
  DashboardWorkspacesWorkspaceSlugRouteImport.update({
    id: '/dashboard/workspaces/$workspaceSlug',
    path: '/dashboard/workspaces/$workspaceSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/workspaces/$workspaceSlug': typeof DashboardWorkspacesWorkspaceSlugRoute
  '/dashboard/workspaces/': typeof DashboardWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/workspaces/$workspaceSlug': typeof DashboardWorkspacesWorkspaceSlugRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/workspaces/$workspaceSlug': typeof DashboardWorkspacesWorkspaceSlugRoute
  '/dashboard/workspaces/': typeof DashboardWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/tasks'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/workspaces/$workspaceSlug'
    | '/dashboard/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/tasks'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/workspaces/$workspaceSlug'
    | '/dashboard/workspaces'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/account'
    | '/dashboard/tasks'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/workspaces/$workspaceSlug'
    | '/dashboard/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DashboardWorkspacesWorkspaceSlugRoute: typeof DashboardWorkspacesWorkspaceSlugRoute
  DashboardWorkspacesIndexRoute: typeof DashboardWorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/dashboard/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces/': {
      id: '/dashboard/workspaces/'
      path: '/dashboard/workspaces'
      fullPath: '/dashboard/workspaces/'
      preLoaderRoute: typeof DashboardWorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces/$workspaceSlug': {
      id: '/dashboard/workspaces/$workspaceSlug'
      path: '/dashboard/workspaces/$workspaceSlug'
      fullPath: '/dashboard/workspaces/$workspaceSlug'
      preLoaderRoute: typeof DashboardWorkspacesWorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DashboardWorkspacesWorkspaceSlugRoute: DashboardWorkspacesWorkspaceSlugRoute,
  DashboardWorkspacesIndexRoute: DashboardWorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
